### ISSUE TITLE
macOS 13 could not install tweedledum with CMake issue

### ISSUE THREAD

**Issue by frogcjn** [boschmitt/tweedledum#174]
### Describe the bug
Could not install tweedledum with pip and macOS 13. (Python 3.10.5)

### Reproducible example code
pip install tweedledum

### Expected behavior
```
Collecting tweedledum
  Using cached tweedledum-1.1.1.tar.gz (4.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: tweedledum
  Building wheel for tweedledum (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for tweedledum (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      /private/var/folders/7l/zgv8pj_d09d1_qm93p8tsc0h0000gn/T/pip-build-env-imba2oow/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:459: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /private/var/folders/7l/zgv8pj_d09d1_qm93p8tsc0h0000gn/T/pip-build-env-imba2oow/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:102: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
        warnings.warn(msg, _ExperimentalProjectMetadata)
      configuration error: `project` must contain ['name'] properties
      /private/var/folders/7l/zgv8pj_d09d1_qm93p8tsc0h0000gn/T/pip-build-env-imba2oow/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:123: _InvalidFile: The given `pyproject.toml` file is invalid and would be ignored.
          !!
      
      
          ############################
          # Invalid `pyproject.toml` #
          ############################
      
          Any configurations in `pyproject.toml` will be ignored.
          Please note that future releases of setuptools will halt the build process
          if an invalid file is given.
      
          To prevent setuptools from considering `pyproject.toml` please
          DO NOT include the `[project]` or `[tool.setuptools]` tables in your file.
      
      
      !!
      
        if _skip_bad_config(project_table, orig_setuptools_table, dist):
        File "/private/var/folders/7l/zgv8pj_d09d1_qm93p8tsc0h0000gn/T/pip-build-env-imba2oow/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/private/var/folders/7l/zgv8pj_d09d1_qm93p8tsc0h0000gn/T/pip-build-env-imba2oow/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/private/var/folders/7l/zgv8pj_d09d1_qm93p8tsc0h0000gn/T/pip-build-env-imba2oow/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tweedledum
Failed to build tweedledum
ERROR: Could not build wheels for tweedledum, which is required to install pyproject.toml-based projects

```

### Information

- **tweedledum version**:
- **Python version**: Python 3.10.5
- **C++ compiler**:
- **Operating system**: macOS 13 developer beta 1 (22A5266r)

**Comment by boschmitt** [comment]
Thanks for reporting this. I will look into to it.
