### ISSUE TITLE
Unable to pip install -- invalid pyproject.toml configuration

### ISSUE THREAD

**Issue by dthebala** [boschmitt/tweedledum#186]
### Describe the bug
Running `pip install tweedledum` yields the following output:
```
Collecting tweedledum
  Downloading tweedledum-1.1.1.tar.gz (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "C:\\Users\\...", line 353, in <module>
          main()
        File "C:\\Users\\...", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\\Users\\...", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\\Users\\...", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\\Users\\...", line 295, in _get_build_requires
          self.run_setup()
        File "C:\\Users\\...", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\\Users\\...", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "C:\\Users\\...", line 488, in setup
          ) = _parse_setuptools_arguments(kw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\\Users\\...", line 221, in _parse_setuptools_arguments
          dist.parse_config_files()
        File "C:\\Users\\...", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "C:\\Users\\...", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\\Users\\...", line 127, in read_configuration
          validate(subset, filepath)
        File "C:\\Users\\...", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


```

### Expected behavior
Successful install.

### Information

- **tweedledum version**: 1.1.1 
- **Python version**: 3.11.1
- **Operating system**: Windows 11

**Comment by WajdiHammami** [comment]
Hi, any updates on this issue ? im facing the same problem right now.

**Comment by diemilio** [comment]
Ran into the same issue. Is this repo still being maintained?

**Comment by VsKendo** [comment]
Same...
my enviornment:
tweedledum version: 1.1.1
Python version: Python 3.11.3
Operating system: MacOS 14.4 (Sonoma)

**Comment by mar-ven** [comment]
I managed to have it running by using a virtual environment with Python 3.10.0

**Comment by mar-ven** [comment]
Indeed, I also tried to manually compile the library, but it seems that it needs PyFrameObject, which has been removed in Python 3.11.
